spring:
  application:
    name: ticket-composite
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  microservices:
    user:
      url: ${USER_SERVICE_URL:http://localhost:8081}
    ticket:
      url: ${TICKET_SERVICE_URL:http://localhost:8082}
    review:
      url: ${REVIEW_SERVICE_URL:http://localhost:8083}